### ISSUE TITLE
    java.lang.IllegalArgumentException: Invalid Transition types

### ISSUE THREAD

**Issue by Sanaebadi97** [shetmobile/MeowBottomNavigation#30]
I am getting crash with this error :
```

 java.lang.IllegalArgumentException: Invalid Transition types
        at androidx.fragment.app.FragmentTransition.chooseImpl(FragmentTransition.java:465)
        at androidx.fragment.app.FragmentTransition.configureTransitionsOrdered(FragmentTransition.java:321)
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:138)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1866)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
```

**Comment by shetmobile** [comment]
please send more info
